Mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('authentication/', include('authentication.urls', namespace='auth')),
    path('cabinet/', include('cabinet.urls', namespace='cabinet')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cabinet/urls.py
from django.urls import path
from . import views

app_name = 'cabinet'
urlpatterns = [
    path('cabinet/<str:user>/', views.cabinet, name="studio"),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name="home"),
    path('post/<slug:slug>', views.post, name="post"),
    path('results', views.search, name="search"),
    path('category/<int:cat_pk>', views.category, name="category"),
]

cabinet/models.py
from django.db import models

# Create your models here.

cabinet/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from main.models import Post
from main.forms import PostAddingForm


special_symbols = " !@#$%^&*()_+-=\'\";:./,<>|"

def checkingForSpecialCharacters(comingString):
    
    f = 0
            
    for i in comingString:
        if i in special_symbols: f = 1
        
    return f == 0


@login_required(redirect_field_name="after", login_url="auth:login")
def cabinet(request, user):
    form = PostAddingForm()
    user_posts = Post.objects.filter(author=request.user.pk)
    
    if request.POST:
        
        postCreatingForm = request.POST.get("postCreatingForm")
        
        if postCreatingForm:
            
            form = PostAddingForm(request.POST, request.FILES)
            
            if form.is_valid() and checkingForSpecialCharacters(request.POST['slug']):
                post = form.save(commit=False)
                post.author = request.user
                post.save()
                messages.success(request, "Post created successfully!")
                return redirect("main:home")
            elif not checkingForSpecialCharacters(request.POST['slug']):
                messages.error(request, "You can not type special symbols and spaces in slug!")
            else:
                messages.error(request, "Smth went wrong")
            
            return redirect("cabinet:studio", request.user)
    
    if request.POST:
        
        editPost = request.POST.get("editPost")
        
        try:
            if editPost:
                p = Post.objects.get(pk=editPost)
                editPostForm = PostAddingForm(instance=p)
                editPost = int(editPost)
        except Exception:
            messages.error(request, "Post not found!")
            return redirect("cabinet:studio", request.user)
    else:
        editPost = 0
        editPostForm = ""
        
    if request.POST:
        
        postUpdatingForm = request.POST.get("postUpdatingForm")
        
        if postUpdatingForm:
            post = Post.objects.get(pk=postUpdatingForm)
            form = PostAddingForm(request.POST, request.FILES, instance=post)
            
            if form.is_valid() and checkingForSpecialCharacters(request.POST['slug']):
                post = form.save()
            elif not checkingForSpecialCharacters(request.POST['slug']):
                messages.error(request, "You can not type special symbols and spaces in slug!")
            else:
                messages.error(request, "Smth went wrong")

            return redirect("cabinet:studio", request.user)

    if request.POST:
        
        deletePost = request.POST.get("deletePost")
        
        try:
            if deletePost:
                Post.objects.get(pk=deletePost).delete()
                messages.success(request, "Post successfully deleted!")
                return redirect("cabinet:studio", request.user)
        except Exception:
            messages.error(request, "Post not found!")
            return redirect("cabinet:studio", request.user)
    
    if request.POST:
        
        deleteAccount = request.POST.get("deleteAccount")
        
        try:
            if deleteAccount:
                User.objects.get(pk=request.user.pk, username=request.user.username).delete()
                messages.success(request, "Account successfully deleted!")
                return redirect("auth:login")
        except Exception:
            messages.error(request, "Account not found!")
            return redirect("auth:login")
    
    data = {
        "form": form,
        "posts": user_posts,
        "editPostid": editPost,
        "editPostForm": editPostForm,
    }
    return render(request, "cabinet/cabinet.html", context=data)

cabinet/templates/cabinet/cabinet.html
{% extends "main/index.html" %}
{% load static %}
{% block style %}
    <!-- custom styles -->
    <link rel="stylesheet" href="{% static 'cabinet/css/cabinet.css' %}">
    <script src="{% static 'cabinet/script.js' %}" defer></script>
{% endblock %}

{% block content %}
<!-- main-block -->
<main>
    {% if messages %}{% for m in messages %}{{ m }}{% endfor %}{% endif %}
    
    <h1>Hello, {{user.username}}!</h1>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h2>Create a post!</h2>
        {{form.as_p}}
        <div><button type="submit" name="postCreatingForm" value="1">Create</button></div>
    </form>

    <h2>Your Posts:</h2>
    {% for p in posts %}
        <div class="cab-post">
            <a href="{% url 'main:post' p.slug %}"><h3>{{ p.name }}</h3></a>
            <form method="POST">{% csrf_token %}<div><button type="submit" name="editPost" value="{{p.pk}}">Edit</button></div></form>
            <form method="POST">{% csrf_token %}<div><button type="submit" name="deletePost" value="{{p.pk}}">Delete</button></div></form>
            {% if editPostid == p.pk %}
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ editPostForm.as_p }}
                    <div><button type="submit" name="postUpdatingForm" value="{{ p.pk }}">Save</button></div>
                </form>
            {% endif %}
        </div>
    {% endfor %}

    <form method="POST" class="deleteForm">
        {% csrf_token %}
        <div><button type="submit" name="deleteAccount" value="1">Delete Account</button></div>
    </form>
</main>
{% endblock content %}