Mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('authentication/', include('authentication.urls', namespace='auth')),
    path('cabinet/', include('cabinet.urls', namespace='cabinet')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path
from . import views

app_name = 'auth'
urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.log_in, name="login"),
    path('logout/', views.log_out, name="logout"),
]

cabinet/urls.py
from django.urls import path
from . import views

app_name = 'cabinet'
urlpatterns = [
    path('cabinet/<str:user>/', views.cabinet, name="studio"),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name="home"),
    path('post/<slug:slug>', views.post, name="post"),
    path('results', views.search, name="search"),
    path('category/<int:cat_pk>', views.category, name="category"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    class CategoryType(models.TextChoices):
        COUNTRIES = 'GLC', ('Global countries')
        NEWS = 'NWS', ('Global news')
        OTHER = 'NO', ("Not in list")
    
    name = models.CharField(max_length=50, unique=True)
    categoryType = models.CharField(max_length=5, choices=CategoryType.choices, default=CategoryType.OTHER)

    def __str__(self) -> str:   
        return (f"Category[ID:{self.pk}]: {self.name}; {self.categoryType}")

default_author = User.objects.get(username='TemporaryAuthor')

class Post(models.Model):
    slug = models.CharField(max_length=25, unique=True)
    image = models.ImageField(blank=True)
    name = models.CharField(max_length=99)
    text = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=default_author.pk)
    date = models.DateTimeField(auto_now_add=True)
    views = models.IntegerField(default=0)

    def __str__(self) -> str:   
        return (f"Post[ID:{self.pk}]: {self.name}")


default_post = Post.objects.get(pk=1)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=default_post.pk)
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=False)
    text = models.TextField(max_length=1000, blank=False)
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:   
        return (f"Comment[ID:{self.pk}]: Author: {self.author}; Date: {self.date}.")

main/forms.py
from django import forms
from .models import Post, Comment

class PostAddingForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea)
    
    class Meta:
        model = Post
        fields = ['slug', 'image', 'name', 'category', 'text']


class CommentForm(forms.ModelForm):
    text = forms.CharField(max_length=1000, widget=forms.Textarea, label="")
    
    class Meta:
        model = Comment
        fields = ['text']

main/views.py
from django.shortcuts import render, redirect
from django.db.models import F
from .models import Post, Comment, Category
from .forms import CommentForm

def index(request):
    
    posts = Post.objects.all().order_by('-date')[:3]
    categories = Category.objects.all()
    message = ""

    data = {
        'posts':posts,
        'categories': categories,
        'message': message,
    }
    
    if request.GET:
        
        query = request.GET.get("search-query")
        
        if query:
            result = Post.objects.filter(name__contains=query) | Post.objects.filter(text__contains=query)
            data["message"] = "Nothing here ... :)"
            data["searchResult"] = result
        
    return render(request, 'main/index.html', context=data)

def post(request, slug):
    
    if request.user.is_authenticated:
        Post.objects.filter(slug = slug).update(views=F('views')+1)
        
    post = Post.objects.get(slug = slug)
    form = CommentForm()
    
    message = "" # Just learning different ways to show messages, by myself and from django contrib messages
    
    if request.POST:
        
        form = CommentForm(request.POST)
        
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            print(comment)
            return redirect("main:post", slug)
        else:
            message = "something went wrong :("
    
    else:
        form = CommentForm()
    
    comments = Comment.objects.filter(post=post).order_by('-date')
    
    if request.POST:
        
        delete_comment = request.POST["delete-comment"]
        
        try:
            if delete_comment:
                delete_comment = delete_comment.split("|")
                comment = Comment.objects.get(pk = delete_comment[0], author=request.user)
                comment.delete()
        except Exception:
            message = "Comment haven't founded"
    
    else:
        pass
    
    data = {
        'post':post,
        'comments':comments,
        'form':form,
    }
    
    return render(request, 'main/post.html', context=data)

def category(request, cat_pk):
    
    category = Category.objects.get(pk=cat_pk)
    posts = Post.objects.filter(category=cat_pk)
    
    data = {
        'cat': category,
        'posts': posts,
    }
    
    return render(request, 'main/category.html', context=data)

def search(request):
    
    if request.GET:
        query = request.GET['search_query']
        result = Post.objects.filter(name__contains=query) | Post.objects.filter(text__contains=query)
        
    data = {
        'searchResult': result,
    }
    
    return render(request, 'main/search.html', context=data)

main/templates/main/category.html
{% extends "main/index.html" %}

{% block content %}
<!-- main-block -->
<main>
    <h3>{{ cat.name }}</h3>
    {% for p in posts %}
    <article>
        {% if p.image %}<img src="{{ p.image.url }}">{% else %}<img src="">{% endif %}
        <div class="card">
            <a href="{% url 'main:post' p.slug %}"><h3 class="card-brand">{{ p.name }}</h3></a>
            <p>{{ p.text }}</p>
            <i>{{ p.author }}</i>
            <i>{{ p.date }}</i>
            <i>{{ p.views }} views</i>
        </div>
    </article>
    {% endfor %}
</main>
{% endblock content %}

main/templates/main/category_tags.html
{% for cat in categories %}
<li><a href="{% url 'main:category' cat.pk %}">{{ cat.name }}</a></li>
{% endfor %}

main/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- custom styles -->
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <script src="{% static 'main/js/script.js' %}" defer></script>
    {% block style %}{% endblock %}

    <title>Document</title>
</head>
<body>
    {% block header %}
    <!-- header -->
    <header>
        <div class="list-header">
            <div class="brand">
                <a href="{% url 'main:home' %}" class="text-decoration-none"><h2 class="navbar-brand fs-2" style="margin:0;padding:0;">Mysite!</h2></a>
                <span>It's my first site on python</span>
            </div>
            <button id="menuToggler">-</button>
        </div>
        <section id="menu">
            <button id="themeLight" class="light">light</button>
            <button id="themeDark" class="dark">dark</button>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="#">{{request.user.username}}</a></li>
                {% else %}
                <li><a href="#">Not logged in</a></li>
                {% endif %}
            </ul>
            <form action="{% url 'main:home' %}" method="GET">
                <input type="search" name="search-query" placeholder="Search">
                <button type="submit">Search</button>
            </form>
        </section>
    </header>
                
    {% endblock %}


    {% block aside %}
    <!-- sidebar -->

    <aside>
        <h2>Navbar</h2>
        <ul>
            {% if user.is_authenticated %}
            <li><a href="{% url 'cabinet:studio' user %}">My Cabinet</a></li>
            <li><a href="{% url 'auth:logout' %}">Log Out</a></li>
            {% else %} 
            <li><a href="{% url 'auth:login' %}">Log In</a></li>
            <li><a href="{% url 'auth:signup' %}">Sign Up</a></li>
            {% endif %}

            <br>

            {% load category_tags %}
            {% show_categories %}
        </ul>
    </aside>

    {% endblock %}


    {% block content %}
    <!-- main-block -->

    <main>
        {% if messages %}{% for m in messages %}{{ m }}{% endfor %}{% endif %}

        {% if searchResult %}
            {% for p in searchResult %}
            <article>
                {% if p.image %}<img src="{{ p.image.url }}">{% else %}<img src="">{% endif %}
                <div class="card">
                    <a href="{% url 'main:post' p.slug %}"><h3 class="card-brand">{{ p.name }}</h3></a>
                    <p>{{ p.text }}</p>
                    <i>{{ p.author }}, {{ p.category.name }}</i>
                    <i>{{ p.date }}</i>
                    <i>{{ p.views }} views</i>
                </div>
            </article>
            {% endfor %}
        {% else %}
            {{message}}
            {% for p in posts %}
            <article>
                {% if p.image %}<img src="{{ p.image.url }}">{% else %}<img src="">{% endif %}
                <div class="card">
                    <a href="{% url 'main:post' p.slug %}"><h3 class="card-brand">{{ p.name }}</h3></a>
                    <p>{{ p.text }}</p>
                    <i>{{ p.author }}</i>
                    <i>{{ p.date }}</i>
                    <i>{{ p.views }} views</i>
                </div>
            </article>
            {% endfor %}
        {% endif %}
    </main>
         
    {% endblock %}

    {% block comments %}


    {% endblock %}


    {% block footer %}
    <!-- footer -->
    
    <footer>
        <p>2025. Site with html&css grid and flexbox layouts.</p>
    </footer>

    {% endblock %}

</body>
</html>

main/templates/main/post.html
{% extends "main/index.html" %}

{% block header %}
<!-- header -->
<header>
    <div class="list-header">
        <div class="brand">
            <a href="{% url 'main:home' %}" class="text-decoration-none"><h2 class="navbar-brand fs-2" style="margin:0;padding:0;">Mysite!</h2></a>
            <span>It's my first site on python</span>
        </div>
        <button id="menuToggler">-</button>
    </div>
    <section id="menu">
        <button id="themeLight" class="light">light</button>
        <button id="themeDark" class="dark">dark</button>
        <ul>
            {% if user.is_authenticated %}
            <li><a href="#">{{request.user.username}}</a></li>
            {% else %}
            <li><a href="#">Not logged in</a></li>
            {% endif %}
        </ul>
        <form action="{% url 'main:search' %}" method="GET">
            <input type="search" name="search_query" placeholder="Search">
            <button type="submit">Search</button>
        </form>
    </section>
</header>
            
{% endblock %}

{% block content %}
<!-- main-block -->
<main>
    <section>
        {% if post.image %}<img src="{{ post.image.url }}">{% else %}<img src="">{% endif %}
        <div class="article-content">
            <h2>{{ post.name }}</h2>
            <p>{{ post.text }}</p>
            <i>{{ post.author }}, {{post.category.name}}</i>
            <i>{{ post.date }}</i>
            <i>{{ post.views }} views</i>
        </div>
    </section>
</main>
{% endblock content %}

{% block comments %}

<section class="comments">
    <h3>Commentaries</h3>
    {% if user.is_authenticated %}
    <h5>Add commentary</h5>
    <form method="POST">
        {% csrf_token %}
        {{message}}
        {{form}}
        <p><button type="submit">Add</button></p>
    </form>
    {% endif %}
    {% for c in comments %}
    <div>
        <p><b>{{ c.author }}</b></p>
        <p class="comment-text">{{ c.text }}</p>
        <i>{{ c.date }}</i>
        {% if c.author.username == user.username and c.author.pk == user.pk %}
        <form method="POST">
            {% csrf_token %}
            <p><button type="submit" name="delete-comment" value="{{c.id}}|{{c.date|date:'Y M D'}}">Delete</button></p>
        </form>
        {% endif %}
    </div>
    {% endfor %}
</section>

{% endblock %}

main/templates/main/search.html
{% extends "main/index.html" %}

{% block content %}
<!-- main-block -->
<main>
    {% if searchResult %}
        {% for p in searchResult %}
        <article>
            {% if p.image %}<img src="{{ p.image.url }}">{% else %}<img src="">{% endif %}
            <div class="card">
                <a href="{% url 'main:post' p.slug %}"><h3 class="card-brand">{{ p.name }}</h3></a>
                <p>{{ p.text }}</p>
                <i>{{ p.date }}</i>
                <i>{{ p.views }} views</i>
            </div>
        </article>
        {% endfor %}
    {% else %}
        <p>Oops... There is no any posts!</p>
    {% endif %}
</main>
{% endblock content %}